/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 27.06.2018 13:13:08
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using Awsd5.BusinessObjects;

namespace Awsd5.ClassicSample
{
	public partial class TwagonCtrl : UserControl, IRecordList
	{
		/*This class contains basic sample UI code, to illustrate usage of the CodeTrigger generated domain objects. Replace this UI layer with your own code*/
		/*WARNING - This class was generated by CodeTrigger. Changes to this file may cause incorrect behaviour and will be lost when the code is regenerated*/
		private int _maxResultsCheck = 3750;
		private BOTwagon _searchBO;
		private ObservableCollection<BOTwagon> _boTwagons;
		private IList<BOTwagon> _boTwagonsCached;
		public TwagonCtrl()
		{
			InitializeComponent();
			resultsBtn.Click += new RoutedEventHandler(resultsBtn_Click);
			updateBtn.Click += new RoutedEventHandler(updateBtn_Click);
			
			_searchBO = new BOTwagon();
			IdTxtBx.DataContext = _searchBO;
			NameTxtBx.DataContext = _searchBO;
			R1TxtBx.DataContext = _searchBO;
			R2TxtBx.DataContext = _searchBO;
			UseridTxtBx.DataContext = _searchBO;
			RealdadaTxtBx.DataContext = _searchBO;
			R3TxtBx.DataContext = _searchBO;
			R4TxtBx.DataContext = _searchBO;
			R5TxtBx.DataContext = _searchBO;
			R6TxtBx.DataContext = _searchBO;
			R7TxtBx.DataContext = _searchBO;
			R8TxtBx.DataContext = _searchBO;
			R9TxtBx.DataContext = _searchBO;
			R10TxtBx.DataContext = _searchBO;
			R11TxtBx.DataContext = _searchBO;
			
			_boTwagons = new ObservableCollection<BOTwagon>();
			_boTwagonsCached = new List<BOTwagon>();
			gridView1.ItemsSource = _boTwagons;
			
		}

		public void ClearRecords()
		{
			_boTwagons.Clear();
		}

		public void LoadRecords(bool checkLimit, bool showCount)
		{
			Cursor origCursor = Mouse.OverrideCursor;
			try
			{
				Mouse.OverrideCursor = Cursors.Wait;
				if(checkLimit)
				{
					int resultCount = BOTwagon.TwagonCollectionFromSearchFieldsCount(_searchBO);
					if((resultCount > _maxResultsCheck) && (MessageBox.Show("Your current filter settings will return " + resultCount.ToString() + " records. Continue with the data retrieval?", "CodeTrigger Sample - data load notification",  MessageBoxButton.YesNo) == MessageBoxResult.No))
						return;
				}
				_boTwagonsCached = BOTwagon.TwagonCollectionFromSearchFields(_searchBO);
				if(checkLimit && (_boTwagonsCached.Count <= _maxResultsCheck) && showCount)
					MessageBox.Show("Your query returned " + _boTwagonsCached.Count + " results.", "Query Results"); 
			
				_boTwagons.Clear();
				foreach(BOTwagon boTwagon in _boTwagonsCached)
					_boTwagons.Add(boTwagon);
			
			}
			catch(Exception ex)
			{
				MessageBox.Show(ex.Message, "CodeTrigger Sample - data load notification");
				return;
			}
			finally	{	Mouse.OverrideCursor = origCursor;	}
		}

		private void resultsBtn_Click(object sender, EventArgs e)
		{
			LoadRecords(true, true);
		}


		private void updateBtn_Click(object sender, EventArgs e)
		{
			if(MessageBox.Show("Are you sure you want to update the data store?", "CodeTrigger Sample - Update notification", MessageBoxButton.YesNo) != MessageBoxResult.Yes)
				return;
				
			Cursor origCursor = Mouse.OverrideCursor;
			try
			{
				Mouse.OverrideCursor = Cursors.Wait;
				foreach(BOTwagon boTwagon in _boTwagons)
				{
					if(_boTwagonsCached.Contains(boTwagon))
					{
						if(!boTwagon.IsDirty) continue;
						try{ boTwagon.Update(); }
						catch(Exception ex)
						{ MessageBox.Show("Error updating record: CodeTrigger has detected a data exception. Possible invalid foreign key reference, missing fields or other error. Exception details follow below.\r\n\r\n" + ex.Message, "CodeTrigger Sample - Update notification"); }
					}
					else
					{
						try{ boTwagon.SaveNew(); }
						catch(Exception ex)
						{ MessageBox.Show("Error saving new record: CodeTrigger has detected a data exception. Possible duplicate primary key, invalid foreign key reference, or missing fields. Exception details follow below.\r\n\r\n" + ex.Message, "CodeTrigger Sample - Update notification"); }
					}
				}
				foreach(BOTwagon boTwagon in _boTwagonsCached)
				{
					if(!_boTwagons.Contains(boTwagon))
					{
						try{ boTwagon.Delete(); }
						catch(Exception ex)
						{ MessageBox.Show("Error deleting record: CodeTrigger has detected a data exception. Possible existing foreign key reference or other error. Exception details follow below.\r\n\r\n" + ex.Message, "CodeTrigger Sample - Update notification"); }
					}
				}
				MessageBox.Show("Update complete.", "CodeTrigger Sample - Update notification");
				StaticBindings.StaticBindings.Instance.UpdateTwagonList();
				LoadRecords(false, false);
			}
			catch
			{	throw;	}
			finally	{	Mouse.OverrideCursor = origCursor;	}
		}
	}
}

