/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 27.06.2018 13:13:07
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;

namespace Awsd5.DataObjects
{
	public partial class DAOMines : DATACONN0_BaseData
	{
		#region member variables
		protected Int32? _id;
		protected string _kodSh;
		protected string _pred;
		protected string _name;
		protected Int32? _kp;
		protected Int32? _kpp;
		protected Int32? _sh11;
		protected Int32? _sh12;
		protected Int32? _sh21;
		protected Int32? _sh22;
		protected Int32? _sh31;
		protected Int32? _sh32;
		protected Int32? _sh41;
		protected Int32? _sh42;
		protected Int32? _sh51;
		protected Int32? _sh52;
		protected Int32? _sh61;
		protected Int32? _sh62;
		protected Int32? _sh71;
		protected Int32? _sh72;
		protected Int32? _sh81;
		protected Int32? _sh82;
		protected Int32? _sh91;
		protected Int32? _sh92;
		protected Int32? _s01;
		protected Int32? _s03;
		protected Int32? _s04;
		protected Int32? _s05;
		protected Int32? _s06;
		protected Int32? _s07;
		protected Int32? _s08;
		protected Int32? _s09;
		protected Int32? _s10;
		protected Int32? _s11;
		protected Int32? _r1;
		protected Int32? _r11;
		#endregion

		#region class methods
		public DAOMines()
		{
		}
		///<Summary>
		///Select one row by primary key(s)
		///This method returns one row from the table mines based on the primary key(s)
		///</Summary>
		///<returns>
		///DAOMines
		///</returns>
		///<parameters>
		///Int32? id
		///</parameters>
		public static DAOMines SelectOne(Int32? id)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprmines_SelectOne;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("mines");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)id?? (object)DBNull.Value));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				DAOMines retObj = null;
				if(dt.Rows.Count > 0)
				{
					retObj = new DAOMines();
					retObj._id					 = Convert.IsDBNull(dt.Rows[0]["id"]) ? (Int32?)null : (Int32?)dt.Rows[0]["id"];
					retObj._kodSh					 = Convert.IsDBNull(dt.Rows[0]["kod_sh"]) ? null : (string)dt.Rows[0]["kod_sh"];
					retObj._pred					 = Convert.IsDBNull(dt.Rows[0]["pred"]) ? null : (string)dt.Rows[0]["pred"];
					retObj._name					 = Convert.IsDBNull(dt.Rows[0]["name"]) ? null : (string)dt.Rows[0]["name"];
					retObj._kp					 = Convert.IsDBNull(dt.Rows[0]["kp"]) ? (Int32?)null : (Int32?)dt.Rows[0]["kp"];
					retObj._kpp					 = Convert.IsDBNull(dt.Rows[0]["kpp"]) ? (Int32?)null : (Int32?)dt.Rows[0]["kpp"];
					retObj._sh11					 = Convert.IsDBNull(dt.Rows[0]["sh11"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh11"];
					retObj._sh12					 = Convert.IsDBNull(dt.Rows[0]["sh12"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh12"];
					retObj._sh21					 = Convert.IsDBNull(dt.Rows[0]["sh21"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh21"];
					retObj._sh22					 = Convert.IsDBNull(dt.Rows[0]["sh22"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh22"];
					retObj._sh31					 = Convert.IsDBNull(dt.Rows[0]["sh31"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh31"];
					retObj._sh32					 = Convert.IsDBNull(dt.Rows[0]["sh32"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh32"];
					retObj._sh41					 = Convert.IsDBNull(dt.Rows[0]["sh41"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh41"];
					retObj._sh42					 = Convert.IsDBNull(dt.Rows[0]["sh42"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh42"];
					retObj._sh51					 = Convert.IsDBNull(dt.Rows[0]["sh51"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh51"];
					retObj._sh52					 = Convert.IsDBNull(dt.Rows[0]["sh52"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh52"];
					retObj._sh61					 = Convert.IsDBNull(dt.Rows[0]["sh61"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh61"];
					retObj._sh62					 = Convert.IsDBNull(dt.Rows[0]["sh62"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh62"];
					retObj._sh71					 = Convert.IsDBNull(dt.Rows[0]["sh71"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh71"];
					retObj._sh72					 = Convert.IsDBNull(dt.Rows[0]["sh72"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh72"];
					retObj._sh81					 = Convert.IsDBNull(dt.Rows[0]["sh81"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh81"];
					retObj._sh82					 = Convert.IsDBNull(dt.Rows[0]["sh82"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh82"];
					retObj._sh91					 = Convert.IsDBNull(dt.Rows[0]["sh91"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh91"];
					retObj._sh92					 = Convert.IsDBNull(dt.Rows[0]["sh92"]) ? (Int32?)null : (Int32?)dt.Rows[0]["sh92"];
					retObj._s01					 = Convert.IsDBNull(dt.Rows[0]["s01"]) ? (Int32?)null : (Int32?)dt.Rows[0]["s01"];
					retObj._s03					 = Convert.IsDBNull(dt.Rows[0]["s03"]) ? (Int32?)null : (Int32?)dt.Rows[0]["s03"];
					retObj._s04					 = Convert.IsDBNull(dt.Rows[0]["s04"]) ? (Int32?)null : (Int32?)dt.Rows[0]["s04"];
					retObj._s05					 = Convert.IsDBNull(dt.Rows[0]["s05"]) ? (Int32?)null : (Int32?)dt.Rows[0]["s05"];
					retObj._s06					 = Convert.IsDBNull(dt.Rows[0]["s06"]) ? (Int32?)null : (Int32?)dt.Rows[0]["s06"];
					retObj._s07					 = Convert.IsDBNull(dt.Rows[0]["s07"]) ? (Int32?)null : (Int32?)dt.Rows[0]["s07"];
					retObj._s08					 = Convert.IsDBNull(dt.Rows[0]["s08"]) ? (Int32?)null : (Int32?)dt.Rows[0]["s08"];
					retObj._s09					 = Convert.IsDBNull(dt.Rows[0]["s09"]) ? (Int32?)null : (Int32?)dt.Rows[0]["s09"];
					retObj._s10					 = Convert.IsDBNull(dt.Rows[0]["s10"]) ? (Int32?)null : (Int32?)dt.Rows[0]["s10"];
					retObj._s11					 = Convert.IsDBNull(dt.Rows[0]["s11"]) ? (Int32?)null : (Int32?)dt.Rows[0]["s11"];
					retObj._r1					 = Convert.IsDBNull(dt.Rows[0]["r1"]) ? (Int32?)null : (Int32?)dt.Rows[0]["r1"];
					retObj._r11					 = Convert.IsDBNull(dt.Rows[0]["r11"]) ? (Int32?)null : (Int32?)dt.Rows[0]["r11"];
				}
				return retObj;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete one row by primary key(s)
		///this method allows the object to delete itself from the table mines based on its primary key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprmines_DeleteOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)_id?? (object)DBNull.Value));

				command.ExecuteNonQuery();

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Insert a new row
		///This method saves a new object to the table mines
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Insert()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprmines_InsertOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _id));
				command.Parameters.Add(new SqlParameter("@kod_sh", SqlDbType.VarChar, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_kodSh?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@pred", SqlDbType.VarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_pred?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@name", SqlDbType.VarChar, 20, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_name?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@kp", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_kp?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@kpp", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_kpp?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh11", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh11?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh12", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh12?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh21", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh21?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh22", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh22?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh31", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh31?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh32", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh32?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh41", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh41?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh42", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh42?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh51", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh51?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh52", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh52?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh61", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh61?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh62", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh62?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh71", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh71?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh72", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh72?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh81", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh81?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh82", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh82?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh91", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh91?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh92", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh92?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s01", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s01?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s03", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s03?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s04", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s04?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s05", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s05?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s06", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s06?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s07", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s07?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s08", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s08?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s09", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s09?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s10", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s10?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s11", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s11?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@r1", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_r1?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@r11", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_r11?? (object)DBNull.Value));

				command.ExecuteNonQuery();

				_id					 = Convert.IsDBNull(command.Parameters["@id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@id"].Value;
				_kodSh					 = Convert.IsDBNull(command.Parameters["@kod_sh"].Value) ? null : (string)command.Parameters["@kod_sh"].Value;
				_pred					 = Convert.IsDBNull(command.Parameters["@pred"].Value) ? null : (string)command.Parameters["@pred"].Value;
				_name					 = Convert.IsDBNull(command.Parameters["@name"].Value) ? null : (string)command.Parameters["@name"].Value;
				_kp					 = Convert.IsDBNull(command.Parameters["@kp"].Value) ? (Int32?)null : (Int32?)command.Parameters["@kp"].Value;
				_kpp					 = Convert.IsDBNull(command.Parameters["@kpp"].Value) ? (Int32?)null : (Int32?)command.Parameters["@kpp"].Value;
				_sh11					 = Convert.IsDBNull(command.Parameters["@sh11"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh11"].Value;
				_sh12					 = Convert.IsDBNull(command.Parameters["@sh12"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh12"].Value;
				_sh21					 = Convert.IsDBNull(command.Parameters["@sh21"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh21"].Value;
				_sh22					 = Convert.IsDBNull(command.Parameters["@sh22"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh22"].Value;
				_sh31					 = Convert.IsDBNull(command.Parameters["@sh31"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh31"].Value;
				_sh32					 = Convert.IsDBNull(command.Parameters["@sh32"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh32"].Value;
				_sh41					 = Convert.IsDBNull(command.Parameters["@sh41"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh41"].Value;
				_sh42					 = Convert.IsDBNull(command.Parameters["@sh42"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh42"].Value;
				_sh51					 = Convert.IsDBNull(command.Parameters["@sh51"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh51"].Value;
				_sh52					 = Convert.IsDBNull(command.Parameters["@sh52"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh52"].Value;
				_sh61					 = Convert.IsDBNull(command.Parameters["@sh61"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh61"].Value;
				_sh62					 = Convert.IsDBNull(command.Parameters["@sh62"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh62"].Value;
				_sh71					 = Convert.IsDBNull(command.Parameters["@sh71"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh71"].Value;
				_sh72					 = Convert.IsDBNull(command.Parameters["@sh72"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh72"].Value;
				_sh81					 = Convert.IsDBNull(command.Parameters["@sh81"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh81"].Value;
				_sh82					 = Convert.IsDBNull(command.Parameters["@sh82"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh82"].Value;
				_sh91					 = Convert.IsDBNull(command.Parameters["@sh91"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh91"].Value;
				_sh92					 = Convert.IsDBNull(command.Parameters["@sh92"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh92"].Value;
				_s01					 = Convert.IsDBNull(command.Parameters["@s01"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s01"].Value;
				_s03					 = Convert.IsDBNull(command.Parameters["@s03"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s03"].Value;
				_s04					 = Convert.IsDBNull(command.Parameters["@s04"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s04"].Value;
				_s05					 = Convert.IsDBNull(command.Parameters["@s05"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s05"].Value;
				_s06					 = Convert.IsDBNull(command.Parameters["@s06"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s06"].Value;
				_s07					 = Convert.IsDBNull(command.Parameters["@s07"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s07"].Value;
				_s08					 = Convert.IsDBNull(command.Parameters["@s08"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s08"].Value;
				_s09					 = Convert.IsDBNull(command.Parameters["@s09"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s09"].Value;
				_s10					 = Convert.IsDBNull(command.Parameters["@s10"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s10"].Value;
				_s11					 = Convert.IsDBNull(command.Parameters["@s11"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s11"].Value;
				_r1					 = Convert.IsDBNull(command.Parameters["@r1"].Value) ? (Int32?)null : (Int32?)command.Parameters["@r1"].Value;
				_r11					 = Convert.IsDBNull(command.Parameters["@r11"].Value) ? (Int32?)null : (Int32?)command.Parameters["@r11"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows
		///This method returns all data rows in the table mines
		///</Summary>
		///<returns>
		///IList-DAOMines.
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<DAOMines> SelectAll()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprmines_SelectAll;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("mines");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DAOMines> objList = new List<DAOMines>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOMines retObj = new DAOMines();
						retObj._id					 = Convert.IsDBNull(row["id"]) ? (Int32?)null : (Int32?)row["id"];
						retObj._kodSh					 = Convert.IsDBNull(row["kod_sh"]) ? null : (string)row["kod_sh"];
						retObj._pred					 = Convert.IsDBNull(row["pred"]) ? null : (string)row["pred"];
						retObj._name					 = Convert.IsDBNull(row["name"]) ? null : (string)row["name"];
						retObj._kp					 = Convert.IsDBNull(row["kp"]) ? (Int32?)null : (Int32?)row["kp"];
						retObj._kpp					 = Convert.IsDBNull(row["kpp"]) ? (Int32?)null : (Int32?)row["kpp"];
						retObj._sh11					 = Convert.IsDBNull(row["sh11"]) ? (Int32?)null : (Int32?)row["sh11"];
						retObj._sh12					 = Convert.IsDBNull(row["sh12"]) ? (Int32?)null : (Int32?)row["sh12"];
						retObj._sh21					 = Convert.IsDBNull(row["sh21"]) ? (Int32?)null : (Int32?)row["sh21"];
						retObj._sh22					 = Convert.IsDBNull(row["sh22"]) ? (Int32?)null : (Int32?)row["sh22"];
						retObj._sh31					 = Convert.IsDBNull(row["sh31"]) ? (Int32?)null : (Int32?)row["sh31"];
						retObj._sh32					 = Convert.IsDBNull(row["sh32"]) ? (Int32?)null : (Int32?)row["sh32"];
						retObj._sh41					 = Convert.IsDBNull(row["sh41"]) ? (Int32?)null : (Int32?)row["sh41"];
						retObj._sh42					 = Convert.IsDBNull(row["sh42"]) ? (Int32?)null : (Int32?)row["sh42"];
						retObj._sh51					 = Convert.IsDBNull(row["sh51"]) ? (Int32?)null : (Int32?)row["sh51"];
						retObj._sh52					 = Convert.IsDBNull(row["sh52"]) ? (Int32?)null : (Int32?)row["sh52"];
						retObj._sh61					 = Convert.IsDBNull(row["sh61"]) ? (Int32?)null : (Int32?)row["sh61"];
						retObj._sh62					 = Convert.IsDBNull(row["sh62"]) ? (Int32?)null : (Int32?)row["sh62"];
						retObj._sh71					 = Convert.IsDBNull(row["sh71"]) ? (Int32?)null : (Int32?)row["sh71"];
						retObj._sh72					 = Convert.IsDBNull(row["sh72"]) ? (Int32?)null : (Int32?)row["sh72"];
						retObj._sh81					 = Convert.IsDBNull(row["sh81"]) ? (Int32?)null : (Int32?)row["sh81"];
						retObj._sh82					 = Convert.IsDBNull(row["sh82"]) ? (Int32?)null : (Int32?)row["sh82"];
						retObj._sh91					 = Convert.IsDBNull(row["sh91"]) ? (Int32?)null : (Int32?)row["sh91"];
						retObj._sh92					 = Convert.IsDBNull(row["sh92"]) ? (Int32?)null : (Int32?)row["sh92"];
						retObj._s01					 = Convert.IsDBNull(row["s01"]) ? (Int32?)null : (Int32?)row["s01"];
						retObj._s03					 = Convert.IsDBNull(row["s03"]) ? (Int32?)null : (Int32?)row["s03"];
						retObj._s04					 = Convert.IsDBNull(row["s04"]) ? (Int32?)null : (Int32?)row["s04"];
						retObj._s05					 = Convert.IsDBNull(row["s05"]) ? (Int32?)null : (Int32?)row["s05"];
						retObj._s06					 = Convert.IsDBNull(row["s06"]) ? (Int32?)null : (Int32?)row["s06"];
						retObj._s07					 = Convert.IsDBNull(row["s07"]) ? (Int32?)null : (Int32?)row["s07"];
						retObj._s08					 = Convert.IsDBNull(row["s08"]) ? (Int32?)null : (Int32?)row["s08"];
						retObj._s09					 = Convert.IsDBNull(row["s09"]) ? (Int32?)null : (Int32?)row["s09"];
						retObj._s10					 = Convert.IsDBNull(row["s10"]) ? (Int32?)null : (Int32?)row["s10"];
						retObj._s11					 = Convert.IsDBNull(row["s11"]) ? (Int32?)null : (Int32?)row["s11"];
						retObj._r1					 = Convert.IsDBNull(row["r1"]) ? (Int32?)null : (Int32?)row["r1"];
						retObj._r11					 = Convert.IsDBNull(row["r11"]) ? (Int32?)null : (Int32?)row["r11"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SelectAllCount()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprmines_SelectAllCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///IList-DAOMines.
		///</returns>
		///<parameters>
		///DAOMines daoMines
		///</parameters>
		public static IList<DAOMines> SelectAllBySearchFields(DAOMines daoMines)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprmines_SelectAllBySearchFields;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("mines");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Id?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@kod_sh", SqlDbType.VarChar, 8, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, (object)daoMines.KodSh?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@pred", SqlDbType.VarChar, 30, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, (object)daoMines.Pred?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@name", SqlDbType.VarChar, 20, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, (object)daoMines.Name?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@kp", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Kp?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@kpp", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Kpp?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh11", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh11?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh12", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh12?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh21", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh21?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh22", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh22?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh31", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh31?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh32", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh32?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh41", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh41?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh42", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh42?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh51", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh51?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh52", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh52?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh61", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh61?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh62", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh62?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh71", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh71?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh72", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh72?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh81", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh81?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh82", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh82?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh91", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh91?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh92", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh92?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s01", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S01?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s03", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S03?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s04", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S04?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s05", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S05?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s06", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S06?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s07", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S07?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s08", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S08?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s09", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S09?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s10", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S10?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s11", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S11?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@r1", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.R1?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@r11", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.R11?? (object)DBNull.Value));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DAOMines> objList = new List<DAOMines>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOMines retObj = new DAOMines();
						retObj._id					 = Convert.IsDBNull(row["id"]) ? (Int32?)null : (Int32?)row["id"];
						retObj._kodSh					 = Convert.IsDBNull(row["kod_sh"]) ? null : (string)row["kod_sh"];
						retObj._pred					 = Convert.IsDBNull(row["pred"]) ? null : (string)row["pred"];
						retObj._name					 = Convert.IsDBNull(row["name"]) ? null : (string)row["name"];
						retObj._kp					 = Convert.IsDBNull(row["kp"]) ? (Int32?)null : (Int32?)row["kp"];
						retObj._kpp					 = Convert.IsDBNull(row["kpp"]) ? (Int32?)null : (Int32?)row["kpp"];
						retObj._sh11					 = Convert.IsDBNull(row["sh11"]) ? (Int32?)null : (Int32?)row["sh11"];
						retObj._sh12					 = Convert.IsDBNull(row["sh12"]) ? (Int32?)null : (Int32?)row["sh12"];
						retObj._sh21					 = Convert.IsDBNull(row["sh21"]) ? (Int32?)null : (Int32?)row["sh21"];
						retObj._sh22					 = Convert.IsDBNull(row["sh22"]) ? (Int32?)null : (Int32?)row["sh22"];
						retObj._sh31					 = Convert.IsDBNull(row["sh31"]) ? (Int32?)null : (Int32?)row["sh31"];
						retObj._sh32					 = Convert.IsDBNull(row["sh32"]) ? (Int32?)null : (Int32?)row["sh32"];
						retObj._sh41					 = Convert.IsDBNull(row["sh41"]) ? (Int32?)null : (Int32?)row["sh41"];
						retObj._sh42					 = Convert.IsDBNull(row["sh42"]) ? (Int32?)null : (Int32?)row["sh42"];
						retObj._sh51					 = Convert.IsDBNull(row["sh51"]) ? (Int32?)null : (Int32?)row["sh51"];
						retObj._sh52					 = Convert.IsDBNull(row["sh52"]) ? (Int32?)null : (Int32?)row["sh52"];
						retObj._sh61					 = Convert.IsDBNull(row["sh61"]) ? (Int32?)null : (Int32?)row["sh61"];
						retObj._sh62					 = Convert.IsDBNull(row["sh62"]) ? (Int32?)null : (Int32?)row["sh62"];
						retObj._sh71					 = Convert.IsDBNull(row["sh71"]) ? (Int32?)null : (Int32?)row["sh71"];
						retObj._sh72					 = Convert.IsDBNull(row["sh72"]) ? (Int32?)null : (Int32?)row["sh72"];
						retObj._sh81					 = Convert.IsDBNull(row["sh81"]) ? (Int32?)null : (Int32?)row["sh81"];
						retObj._sh82					 = Convert.IsDBNull(row["sh82"]) ? (Int32?)null : (Int32?)row["sh82"];
						retObj._sh91					 = Convert.IsDBNull(row["sh91"]) ? (Int32?)null : (Int32?)row["sh91"];
						retObj._sh92					 = Convert.IsDBNull(row["sh92"]) ? (Int32?)null : (Int32?)row["sh92"];
						retObj._s01					 = Convert.IsDBNull(row["s01"]) ? (Int32?)null : (Int32?)row["s01"];
						retObj._s03					 = Convert.IsDBNull(row["s03"]) ? (Int32?)null : (Int32?)row["s03"];
						retObj._s04					 = Convert.IsDBNull(row["s04"]) ? (Int32?)null : (Int32?)row["s04"];
						retObj._s05					 = Convert.IsDBNull(row["s05"]) ? (Int32?)null : (Int32?)row["s05"];
						retObj._s06					 = Convert.IsDBNull(row["s06"]) ? (Int32?)null : (Int32?)row["s06"];
						retObj._s07					 = Convert.IsDBNull(row["s07"]) ? (Int32?)null : (Int32?)row["s07"];
						retObj._s08					 = Convert.IsDBNull(row["s08"]) ? (Int32?)null : (Int32?)row["s08"];
						retObj._s09					 = Convert.IsDBNull(row["s09"]) ? (Int32?)null : (Int32?)row["s09"];
						retObj._s10					 = Convert.IsDBNull(row["s10"]) ? (Int32?)null : (Int32?)row["s10"];
						retObj._s11					 = Convert.IsDBNull(row["s11"]) ? (Int32?)null : (Int32?)row["s11"];
						retObj._r1					 = Convert.IsDBNull(row["r1"]) ? (Int32?)null : (Int32?)row["r1"];
						retObj._r11					 = Convert.IsDBNull(row["r11"]) ? (Int32?)null : (Int32?)row["r11"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///DAOMines daoMines
		///</parameters>
		public static Int32 SelectAllBySearchFieldsCount(DAOMines daoMines)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprmines_SelectAllBySearchFieldsCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Id?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@kod_sh", SqlDbType.VarChar, 8, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, (object)daoMines.KodSh?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@pred", SqlDbType.VarChar, 30, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, (object)daoMines.Pred?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@name", SqlDbType.VarChar, 20, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, (object)daoMines.Name?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@kp", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Kp?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@kpp", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Kpp?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh11", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh11?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh12", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh12?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh21", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh21?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh22", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh22?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh31", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh31?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh32", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh32?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh41", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh41?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh42", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh42?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh51", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh51?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh52", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh52?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh61", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh61?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh62", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh62?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh71", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh71?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh72", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh72?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh81", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh81?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh82", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh82?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh91", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh91?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh92", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.Sh92?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s01", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S01?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s03", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S03?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s04", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S04?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s05", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S05?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s06", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S06?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s07", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S07?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s08", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S08?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s09", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S09?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s10", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S10?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s11", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.S11?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@r1", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.R1?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@r11", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoMines.R11?? (object)DBNull.Value));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Update one row by primary key(s)
		///This method allows the object to update itself in the table mines based on its primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Update()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprmines_UpdateOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_id?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@kod_sh", SqlDbType.VarChar, 8, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_kodSh?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@pred", SqlDbType.VarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_pred?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@name", SqlDbType.VarChar, 20, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_name?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@kp", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_kp?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@kpp", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_kpp?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh11", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh11?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh12", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh12?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh21", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh21?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh22", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh22?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh31", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh31?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh32", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh32?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh41", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh41?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh42", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh42?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh51", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh51?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh52", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh52?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh61", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh61?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh62", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh62?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh71", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh71?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh72", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh72?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh81", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh81?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh82", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh82?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh91", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh91?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@sh92", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_sh92?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s01", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s01?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s03", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s03?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s04", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s04?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s05", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s05?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s06", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s06?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s07", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s07?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s08", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s08?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s09", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s09?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s10", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s10?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@s11", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_s11?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@r1", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_r1?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@r11", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_r11?? (object)DBNull.Value));

				command.ExecuteNonQuery();

				_id					 = Convert.IsDBNull(command.Parameters["@id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@id"].Value;
				_kodSh					 = Convert.IsDBNull(command.Parameters["@kod_sh"].Value) ? null : (string)command.Parameters["@kod_sh"].Value;
				_pred					 = Convert.IsDBNull(command.Parameters["@pred"].Value) ? null : (string)command.Parameters["@pred"].Value;
				_name					 = Convert.IsDBNull(command.Parameters["@name"].Value) ? null : (string)command.Parameters["@name"].Value;
				_kp					 = Convert.IsDBNull(command.Parameters["@kp"].Value) ? (Int32?)null : (Int32?)command.Parameters["@kp"].Value;
				_kpp					 = Convert.IsDBNull(command.Parameters["@kpp"].Value) ? (Int32?)null : (Int32?)command.Parameters["@kpp"].Value;
				_sh11					 = Convert.IsDBNull(command.Parameters["@sh11"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh11"].Value;
				_sh12					 = Convert.IsDBNull(command.Parameters["@sh12"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh12"].Value;
				_sh21					 = Convert.IsDBNull(command.Parameters["@sh21"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh21"].Value;
				_sh22					 = Convert.IsDBNull(command.Parameters["@sh22"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh22"].Value;
				_sh31					 = Convert.IsDBNull(command.Parameters["@sh31"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh31"].Value;
				_sh32					 = Convert.IsDBNull(command.Parameters["@sh32"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh32"].Value;
				_sh41					 = Convert.IsDBNull(command.Parameters["@sh41"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh41"].Value;
				_sh42					 = Convert.IsDBNull(command.Parameters["@sh42"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh42"].Value;
				_sh51					 = Convert.IsDBNull(command.Parameters["@sh51"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh51"].Value;
				_sh52					 = Convert.IsDBNull(command.Parameters["@sh52"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh52"].Value;
				_sh61					 = Convert.IsDBNull(command.Parameters["@sh61"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh61"].Value;
				_sh62					 = Convert.IsDBNull(command.Parameters["@sh62"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh62"].Value;
				_sh71					 = Convert.IsDBNull(command.Parameters["@sh71"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh71"].Value;
				_sh72					 = Convert.IsDBNull(command.Parameters["@sh72"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh72"].Value;
				_sh81					 = Convert.IsDBNull(command.Parameters["@sh81"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh81"].Value;
				_sh82					 = Convert.IsDBNull(command.Parameters["@sh82"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh82"].Value;
				_sh91					 = Convert.IsDBNull(command.Parameters["@sh91"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh91"].Value;
				_sh92					 = Convert.IsDBNull(command.Parameters["@sh92"].Value) ? (Int32?)null : (Int32?)command.Parameters["@sh92"].Value;
				_s01					 = Convert.IsDBNull(command.Parameters["@s01"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s01"].Value;
				_s03					 = Convert.IsDBNull(command.Parameters["@s03"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s03"].Value;
				_s04					 = Convert.IsDBNull(command.Parameters["@s04"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s04"].Value;
				_s05					 = Convert.IsDBNull(command.Parameters["@s05"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s05"].Value;
				_s06					 = Convert.IsDBNull(command.Parameters["@s06"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s06"].Value;
				_s07					 = Convert.IsDBNull(command.Parameters["@s07"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s07"].Value;
				_s08					 = Convert.IsDBNull(command.Parameters["@s08"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s08"].Value;
				_s09					 = Convert.IsDBNull(command.Parameters["@s09"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s09"].Value;
				_s10					 = Convert.IsDBNull(command.Parameters["@s10"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s10"].Value;
				_s11					 = Convert.IsDBNull(command.Parameters["@s11"].Value) ? (Int32?)null : (Int32?)command.Parameters["@s11"].Value;
				_r1					 = Convert.IsDBNull(command.Parameters["@r1"].Value) ? (Int32?)null : (Int32?)command.Parameters["@r1"].Value;
				_r11					 = Convert.IsDBNull(command.Parameters["@r11"].Value) ? (Int32?)null : (Int32?)command.Parameters["@r11"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		#endregion

		#region member properties

		public Int32? Id
		{
			get
			{
				return _id;
			}
			set
			{
				_id = value;
			}
		}

		public string KodSh
		{
			get
			{
				return _kodSh;
			}
			set
			{
				_kodSh = value;
			}
		}

		public string Pred
		{
			get
			{
				return _pred;
			}
			set
			{
				_pred = value;
			}
		}

		public string Name
		{
			get
			{
				return _name;
			}
			set
			{
				_name = value;
			}
		}

		public Int32? Kp
		{
			get
			{
				return _kp;
			}
			set
			{
				_kp = value;
			}
		}

		public Int32? Kpp
		{
			get
			{
				return _kpp;
			}
			set
			{
				_kpp = value;
			}
		}

		public Int32? Sh11
		{
			get
			{
				return _sh11;
			}
			set
			{
				_sh11 = value;
			}
		}

		public Int32? Sh12
		{
			get
			{
				return _sh12;
			}
			set
			{
				_sh12 = value;
			}
		}

		public Int32? Sh21
		{
			get
			{
				return _sh21;
			}
			set
			{
				_sh21 = value;
			}
		}

		public Int32? Sh22
		{
			get
			{
				return _sh22;
			}
			set
			{
				_sh22 = value;
			}
		}

		public Int32? Sh31
		{
			get
			{
				return _sh31;
			}
			set
			{
				_sh31 = value;
			}
		}

		public Int32? Sh32
		{
			get
			{
				return _sh32;
			}
			set
			{
				_sh32 = value;
			}
		}

		public Int32? Sh41
		{
			get
			{
				return _sh41;
			}
			set
			{
				_sh41 = value;
			}
		}

		public Int32? Sh42
		{
			get
			{
				return _sh42;
			}
			set
			{
				_sh42 = value;
			}
		}

		public Int32? Sh51
		{
			get
			{
				return _sh51;
			}
			set
			{
				_sh51 = value;
			}
		}

		public Int32? Sh52
		{
			get
			{
				return _sh52;
			}
			set
			{
				_sh52 = value;
			}
		}

		public Int32? Sh61
		{
			get
			{
				return _sh61;
			}
			set
			{
				_sh61 = value;
			}
		}

		public Int32? Sh62
		{
			get
			{
				return _sh62;
			}
			set
			{
				_sh62 = value;
			}
		}

		public Int32? Sh71
		{
			get
			{
				return _sh71;
			}
			set
			{
				_sh71 = value;
			}
		}

		public Int32? Sh72
		{
			get
			{
				return _sh72;
			}
			set
			{
				_sh72 = value;
			}
		}

		public Int32? Sh81
		{
			get
			{
				return _sh81;
			}
			set
			{
				_sh81 = value;
			}
		}

		public Int32? Sh82
		{
			get
			{
				return _sh82;
			}
			set
			{
				_sh82 = value;
			}
		}

		public Int32? Sh91
		{
			get
			{
				return _sh91;
			}
			set
			{
				_sh91 = value;
			}
		}

		public Int32? Sh92
		{
			get
			{
				return _sh92;
			}
			set
			{
				_sh92 = value;
			}
		}

		public Int32? S01
		{
			get
			{
				return _s01;
			}
			set
			{
				_s01 = value;
			}
		}

		public Int32? S03
		{
			get
			{
				return _s03;
			}
			set
			{
				_s03 = value;
			}
		}

		public Int32? S04
		{
			get
			{
				return _s04;
			}
			set
			{
				_s04 = value;
			}
		}

		public Int32? S05
		{
			get
			{
				return _s05;
			}
			set
			{
				_s05 = value;
			}
		}

		public Int32? S06
		{
			get
			{
				return _s06;
			}
			set
			{
				_s06 = value;
			}
		}

		public Int32? S07
		{
			get
			{
				return _s07;
			}
			set
			{
				_s07 = value;
			}
		}

		public Int32? S08
		{
			get
			{
				return _s08;
			}
			set
			{
				_s08 = value;
			}
		}

		public Int32? S09
		{
			get
			{
				return _s09;
			}
			set
			{
				_s09 = value;
			}
		}

		public Int32? S10
		{
			get
			{
				return _s10;
			}
			set
			{
				_s10 = value;
			}
		}

		public Int32? S11
		{
			get
			{
				return _s11;
			}
			set
			{
				_s11 = value;
			}
		}

		public Int32? R1
		{
			get
			{
				return _r1;
			}
			set
			{
				_r1 = value;
			}
		}

		public Int32? R11
		{
			get
			{
				return _r11;
			}
			set
			{
				_r11 = value;
			}
		}

		#endregion
	}
}

#region inline sql procs
namespace Awsd5.DataObjects
{
	public partial class InlineProcs
	{
		internal static string ctprmines_SelectOne = @"
			-- Select one row based on the primary key(s)
			-- selects all rows from the table
			SELECT 
			[id]
			,[kod_sh]
			,[pred]
			,[name]
			,[kp]
			,[kpp]
			,[sh11]
			,[sh12]
			,[sh21]
			,[sh22]
			,[sh31]
			,[sh32]
			,[sh41]
			,[sh42]
			,[sh51]
			,[sh52]
			,[sh61]
			,[sh62]
			,[sh71]
			,[sh72]
			,[sh81]
			,[sh82]
			,[sh91]
			,[sh92]
			,[s01]
			,[s03]
			,[s04]
			,[s05]
			,[s06]
			,[s07]
			,[s08]
			,[s09]
			,[s10]
			,[s11]
			,[r1]
			,[r11]
			FROM [dbo].[mines]
			WHERE 
			[id] = @id
			";

		internal static string ctprmines_DeleteOne = @"
			-- Delete a row based on the primary key(s)
			-- delete all matching from the table
			DELETE [dbo].[mines]
			WHERE 
			[id] = @id
			";

		internal static string ctprmines_InsertOne = @"
			-- Insert a new row
			-- inserts a new row into the table
			INSERT [dbo].[mines]
			(
			[kod_sh]
			,[pred]
			,[name]
			,[kp]
			,[kpp]
			,[sh11]
			,[sh12]
			,[sh21]
			,[sh22]
			,[sh31]
			,[sh32]
			,[sh41]
			,[sh42]
			,[sh51]
			,[sh52]
			,[sh61]
			,[sh62]
			,[sh71]
			,[sh72]
			,[sh81]
			,[sh82]
			,[sh91]
			,[sh92]
			,[s01]
			,[s03]
			,[s04]
			,[s05]
			,[s06]
			,[s07]
			,[s08]
			,[s09]
			,[s10]
			,[s11]
			,[r1]
			,[r11]
			)
			VALUES
			(
			@kod_sh
			,@pred
			,@name
			,@kp
			,@kpp
			,@sh11
			,@sh12
			,@sh21
			,@sh22
			,@sh31
			,@sh32
			,@sh41
			,@sh42
			,@sh51
			,@sh52
			,@sh61
			,@sh62
			,@sh71
			,@sh72
			,@sh81
			,@sh82
			,@sh91
			,@sh92
			,@s01
			,@s03
			,@s04
			,@s05
			,@s06
			,@s07
			,@s08
			,@s09
			,@s10
			,@s11
			,@r1
			,@r11
			)
			SELECT 
			@id = [id]
			,@kod_sh = [kod_sh]
			,@pred = [pred]
			,@name = [name]
			,@kp = [kp]
			,@kpp = [kpp]
			,@sh11 = [sh11]
			,@sh12 = [sh12]
			,@sh21 = [sh21]
			,@sh22 = [sh22]
			,@sh31 = [sh31]
			,@sh32 = [sh32]
			,@sh41 = [sh41]
			,@sh42 = [sh42]
			,@sh51 = [sh51]
			,@sh52 = [sh52]
			,@sh61 = [sh61]
			,@sh62 = [sh62]
			,@sh71 = [sh71]
			,@sh72 = [sh72]
			,@sh81 = [sh81]
			,@sh82 = [sh82]
			,@sh91 = [sh91]
			,@sh92 = [sh92]
			,@s01 = [s01]
			,@s03 = [s03]
			,@s04 = [s04]
			,@s05 = [s05]
			,@s06 = [s06]
			,@s07 = [s07]
			,@s08 = [s08]
			,@s09 = [s09]
			,@s10 = [s10]
			,@s11 = [s11]
			,@r1 = [r1]
			,@r11 = [r11]
			FROM [dbo].[mines]
			WHERE 
			id = SCOPE_IDENTITY()
			";

		internal static string ctprmines_SelectAll = @"
			-- Select All rows
			-- selects all rows from the table
			SELECT 
			[id]
			,[kod_sh]
			,[pred]
			,[name]
			,[kp]
			,[kpp]
			,[sh11]
			,[sh12]
			,[sh21]
			,[sh22]
			,[sh31]
			,[sh32]
			,[sh41]
			,[sh42]
			,[sh51]
			,[sh52]
			,[sh61]
			,[sh62]
			,[sh71]
			,[sh72]
			,[sh81]
			,[sh82]
			,[sh91]
			,[sh92]
			,[s01]
			,[s03]
			,[s04]
			,[s05]
			,[s06]
			,[s07]
			,[s08]
			,[s09]
			,[s10]
			,[s11]
			,[r1]
			,[r11]
			FROM [dbo].[mines]
			";

		internal static string ctprmines_SelectAllCount = @"
			
			-- selects count of all rows from the table
			SELECT COUNT(*)
			FROM [dbo].[mines]
			";

		internal static string ctprmines_SelectAllBySearchFields = @"
			
			-- selects all rows from the table according to search criteria
			SELECT 
			[id],
			[kod_sh],
			[pred],
			[name],
			[kp],
			[kpp],
			[sh11],
			[sh12],
			[sh21],
			[sh22],
			[sh31],
			[sh32],
			[sh41],
			[sh42],
			[sh51],
			[sh52],
			[sh61],
			[sh62],
			[sh71],
			[sh72],
			[sh81],
			[sh82],
			[sh91],
			[sh92],
			[s01],
			[s03],
			[s04],
			[s05],
			[s06],
			[s07],
			[s08],
			[s09],
			[s10],
			[s11],
			[r1],
			[r11]
			FROM [dbo].[mines]
			WHERE 
			([id] LIKE @id OR @id is null)
			AND ([kod_sh] LIKE @kod_sh OR @kod_sh is null)
			AND ([pred] LIKE @pred OR @pred is null)
			AND ([name] LIKE @name OR @name is null)
			AND ([kp] LIKE @kp OR @kp is null)
			AND ([kpp] LIKE @kpp OR @kpp is null)
			AND ([sh11] LIKE @sh11 OR @sh11 is null)
			AND ([sh12] LIKE @sh12 OR @sh12 is null)
			AND ([sh21] LIKE @sh21 OR @sh21 is null)
			AND ([sh22] LIKE @sh22 OR @sh22 is null)
			AND ([sh31] LIKE @sh31 OR @sh31 is null)
			AND ([sh32] LIKE @sh32 OR @sh32 is null)
			AND ([sh41] LIKE @sh41 OR @sh41 is null)
			AND ([sh42] LIKE @sh42 OR @sh42 is null)
			AND ([sh51] LIKE @sh51 OR @sh51 is null)
			AND ([sh52] LIKE @sh52 OR @sh52 is null)
			AND ([sh61] LIKE @sh61 OR @sh61 is null)
			AND ([sh62] LIKE @sh62 OR @sh62 is null)
			AND ([sh71] LIKE @sh71 OR @sh71 is null)
			AND ([sh72] LIKE @sh72 OR @sh72 is null)
			AND ([sh81] LIKE @sh81 OR @sh81 is null)
			AND ([sh82] LIKE @sh82 OR @sh82 is null)
			AND ([sh91] LIKE @sh91 OR @sh91 is null)
			AND ([sh92] LIKE @sh92 OR @sh92 is null)
			AND ([s01] LIKE @s01 OR @s01 is null)
			AND ([s03] LIKE @s03 OR @s03 is null)
			AND ([s04] LIKE @s04 OR @s04 is null)
			AND ([s05] LIKE @s05 OR @s05 is null)
			AND ([s06] LIKE @s06 OR @s06 is null)
			AND ([s07] LIKE @s07 OR @s07 is null)
			AND ([s08] LIKE @s08 OR @s08 is null)
			AND ([s09] LIKE @s09 OR @s09 is null)
			AND ([s10] LIKE @s10 OR @s10 is null)
			AND ([s11] LIKE @s11 OR @s11 is null)
			AND ([r1] LIKE @r1 OR @r1 is null)
			AND ([r11] LIKE @r11 OR @r11 is null)
			";

		internal static string ctprmines_SelectAllBySearchFieldsCount = @"
			-- Get count of rows returnable by this query
			-- selects count of all rows from the table according to search criteria
			SELECT COUNT(*)
			FROM [dbo].[mines]
			WHERE 
			([id] LIKE @id OR @id is null)
			AND ([kod_sh] LIKE @kod_sh OR @kod_sh is null)
			AND ([pred] LIKE @pred OR @pred is null)
			AND ([name] LIKE @name OR @name is null)
			AND ([kp] LIKE @kp OR @kp is null)
			AND ([kpp] LIKE @kpp OR @kpp is null)
			AND ([sh11] LIKE @sh11 OR @sh11 is null)
			AND ([sh12] LIKE @sh12 OR @sh12 is null)
			AND ([sh21] LIKE @sh21 OR @sh21 is null)
			AND ([sh22] LIKE @sh22 OR @sh22 is null)
			AND ([sh31] LIKE @sh31 OR @sh31 is null)
			AND ([sh32] LIKE @sh32 OR @sh32 is null)
			AND ([sh41] LIKE @sh41 OR @sh41 is null)
			AND ([sh42] LIKE @sh42 OR @sh42 is null)
			AND ([sh51] LIKE @sh51 OR @sh51 is null)
			AND ([sh52] LIKE @sh52 OR @sh52 is null)
			AND ([sh61] LIKE @sh61 OR @sh61 is null)
			AND ([sh62] LIKE @sh62 OR @sh62 is null)
			AND ([sh71] LIKE @sh71 OR @sh71 is null)
			AND ([sh72] LIKE @sh72 OR @sh72 is null)
			AND ([sh81] LIKE @sh81 OR @sh81 is null)
			AND ([sh82] LIKE @sh82 OR @sh82 is null)
			AND ([sh91] LIKE @sh91 OR @sh91 is null)
			AND ([sh92] LIKE @sh92 OR @sh92 is null)
			AND ([s01] LIKE @s01 OR @s01 is null)
			AND ([s03] LIKE @s03 OR @s03 is null)
			AND ([s04] LIKE @s04 OR @s04 is null)
			AND ([s05] LIKE @s05 OR @s05 is null)
			AND ([s06] LIKE @s06 OR @s06 is null)
			AND ([s07] LIKE @s07 OR @s07 is null)
			AND ([s08] LIKE @s08 OR @s08 is null)
			AND ([s09] LIKE @s09 OR @s09 is null)
			AND ([s10] LIKE @s10 OR @s10 is null)
			AND ([s11] LIKE @s11 OR @s11 is null)
			AND ([r1] LIKE @r1 OR @r1 is null)
			AND ([r11] LIKE @r11 OR @r11 is null)
			";

		internal static string ctprmines_UpdateOne = @"
			-- Update one row based on the primary key(s)
			-- updates a row in the table based on the primary key
			
			UPDATE [dbo].[mines]
			SET
			[kod_sh] = @kod_sh
			,[pred] = @pred
			,[name] = @name
			,[kp] = @kp
			,[kpp] = @kpp
			,[sh11] = @sh11
			,[sh12] = @sh12
			,[sh21] = @sh21
			,[sh22] = @sh22
			,[sh31] = @sh31
			,[sh32] = @sh32
			,[sh41] = @sh41
			,[sh42] = @sh42
			,[sh51] = @sh51
			,[sh52] = @sh52
			,[sh61] = @sh61
			,[sh62] = @sh62
			,[sh71] = @sh71
			,[sh72] = @sh72
			,[sh81] = @sh81
			,[sh82] = @sh82
			,[sh91] = @sh91
			,[sh92] = @sh92
			,[s01] = @s01
			,[s03] = @s03
			,[s04] = @s04
			,[s05] = @s05
			,[s06] = @s06
			,[s07] = @s07
			,[s08] = @s08
			,[s09] = @s09
			,[s10] = @s10
			,[s11] = @s11
			,[r1] = @r1
			,[r11] = @r11
			WHERE 
			[id] = @id
			SELECT 
			@id = [id]
			,@kod_sh = [kod_sh]
			,@pred = [pred]
			,@name = [name]
			,@kp = [kp]
			,@kpp = [kpp]
			,@sh11 = [sh11]
			,@sh12 = [sh12]
			,@sh21 = [sh21]
			,@sh22 = [sh22]
			,@sh31 = [sh31]
			,@sh32 = [sh32]
			,@sh41 = [sh41]
			,@sh42 = [sh42]
			,@sh51 = [sh51]
			,@sh52 = [sh52]
			,@sh61 = [sh61]
			,@sh62 = [sh62]
			,@sh71 = [sh71]
			,@sh72 = [sh72]
			,@sh81 = [sh81]
			,@sh82 = [sh82]
			,@sh91 = [sh91]
			,@sh92 = [sh92]
			,@s01 = [s01]
			,@s03 = [s03]
			,@s04 = [s04]
			,@s05 = [s05]
			,@s06 = [s06]
			,@s07 = [s07]
			,@s08 = [s08]
			,@s09 = [s09]
			,@s10 = [s10]
			,@s11 = [s11]
			,@r1 = [r1]
			,@r11 = [r11]
			FROM [dbo].[mines]
			WHERE 
			[id] = @id
			";

	}
}
#endregion
