/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 27.06.2018 13:13:07
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;

namespace Awsd5.DataObjects
{
	public partial class DAOProducts : DATACONN0_BaseData
	{
		#region member variables
		protected Int32? _id;
		protected string _name;
		protected string _shortname;
		protected Int64? _externalid;
		protected Int32? _producttypeid;
		#endregion

		#region class methods
		public DAOProducts()
		{
		}
		///<Summary>
		///Select one row by primary key(s)
		///This method returns one row from the table products based on the primary key(s)
		///</Summary>
		///<returns>
		///DAOProducts
		///</returns>
		///<parameters>
		///Int32? id
		///</parameters>
		public static DAOProducts SelectOne(Int32? id)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprproducts_SelectOne;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("products");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)id?? (object)DBNull.Value));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				DAOProducts retObj = null;
				if(dt.Rows.Count > 0)
				{
					retObj = new DAOProducts();
					retObj._id					 = Convert.IsDBNull(dt.Rows[0]["id"]) ? (Int32?)null : (Int32?)dt.Rows[0]["id"];
					retObj._name					 = Convert.IsDBNull(dt.Rows[0]["name"]) ? null : (string)dt.Rows[0]["name"];
					retObj._shortname					 = Convert.IsDBNull(dt.Rows[0]["shortname"]) ? null : (string)dt.Rows[0]["shortname"];
					retObj._externalid					 = Convert.IsDBNull(dt.Rows[0]["externalid"]) ? (Int64?)null : (Int64?)dt.Rows[0]["externalid"];
					retObj._producttypeid					 = Convert.IsDBNull(dt.Rows[0]["producttypeid"]) ? (Int32?)null : (Int32?)dt.Rows[0]["producttypeid"];
				}
				return retObj;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete one row by primary key(s)
		///this method allows the object to delete itself from the table products based on its primary key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprproducts_DeleteOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)_id?? (object)DBNull.Value));

				command.ExecuteNonQuery();

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows by foreign key
		///This method returns all data rows in the table products based on a foreign key
		///</Summary>
		///<returns>
		///IList-DAOProducts.
		///</returns>
		///<parameters>
		///Int32? producttypeid
		///</parameters>
		public static IList<DAOProducts> SelectAllByProducttypeid(Int32? producttypeid)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprproducts_SelectAllByProducttypeid;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("products");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(new SqlParameter("@producttypeid", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)producttypeid?? (object)DBNull.Value));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DAOProducts> objList = new List<DAOProducts>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOProducts retObj = new DAOProducts();
						retObj._id					 = Convert.IsDBNull(row["id"]) ? (Int32?)null : (Int32?)row["id"];
						retObj._name					 = Convert.IsDBNull(row["name"]) ? null : (string)row["name"];
						retObj._shortname					 = Convert.IsDBNull(row["shortname"]) ? null : (string)row["shortname"];
						retObj._externalid					 = Convert.IsDBNull(row["externalid"]) ? (Int64?)null : (Int64?)row["externalid"];
						retObj._producttypeid					 = Convert.IsDBNull(row["producttypeid"]) ? (Int32?)null : (Int32?)row["producttypeid"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///Int32? producttypeid
		///</parameters>
		public static Int32 SelectAllByProducttypeidCount(Int32? producttypeid)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprproducts_SelectAllByProducttypeidCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(new SqlParameter("@producttypeid", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)producttypeid?? (object)DBNull.Value));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete all by foreign key
		///This method deletes all rows in the table products with a given foreign key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DATACONN0_TxConnectionProvider connectionProvider, Int32? producttypeid
		///</parameters>
		public static void DeleteAllByProducttypeid(DATACONN0_TxConnectionProvider connectionProvider, Int32? producttypeid)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprproducts_DeleteAllByProducttypeid;
			command.CommandType = CommandType.Text;
			command.Connection = connectionProvider.Connection;
			command.Transaction = connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@producttypeid", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)producttypeid?? (object)DBNull.Value));

				command.ExecuteNonQuery();

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Insert a new row
		///This method saves a new object to the table products
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Insert()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprproducts_InsertOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _id));
				command.Parameters.Add(new SqlParameter("@name", SqlDbType.VarChar, 255, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_name?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@shortname", SqlDbType.VarChar, 255, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_shortname?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@externalid", SqlDbType.BigInt, 8, ParameterDirection.InputOutput, true, 19, 0, "", DataRowVersion.Proposed, (object)_externalid?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@producttypeid", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_producttypeid?? (object)DBNull.Value));

				command.ExecuteNonQuery();

				_id					 = Convert.IsDBNull(command.Parameters["@id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@id"].Value;
				_name					 = Convert.IsDBNull(command.Parameters["@name"].Value) ? null : (string)command.Parameters["@name"].Value;
				_shortname					 = Convert.IsDBNull(command.Parameters["@shortname"].Value) ? null : (string)command.Parameters["@shortname"].Value;
				_externalid					 = Convert.IsDBNull(command.Parameters["@externalid"].Value) ? (Int64?)null : (Int64?)command.Parameters["@externalid"].Value;
				_producttypeid					 = Convert.IsDBNull(command.Parameters["@producttypeid"].Value) ? (Int32?)null : (Int32?)command.Parameters["@producttypeid"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows
		///This method returns all data rows in the table products
		///</Summary>
		///<returns>
		///IList-DAOProducts.
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<DAOProducts> SelectAll()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprproducts_SelectAll;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("products");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DAOProducts> objList = new List<DAOProducts>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOProducts retObj = new DAOProducts();
						retObj._id					 = Convert.IsDBNull(row["id"]) ? (Int32?)null : (Int32?)row["id"];
						retObj._name					 = Convert.IsDBNull(row["name"]) ? null : (string)row["name"];
						retObj._shortname					 = Convert.IsDBNull(row["shortname"]) ? null : (string)row["shortname"];
						retObj._externalid					 = Convert.IsDBNull(row["externalid"]) ? (Int64?)null : (Int64?)row["externalid"];
						retObj._producttypeid					 = Convert.IsDBNull(row["producttypeid"]) ? (Int32?)null : (Int32?)row["producttypeid"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SelectAllCount()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprproducts_SelectAllCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///IList-DAOProducts.
		///</returns>
		///<parameters>
		///DAOProducts daoProducts
		///</parameters>
		public static IList<DAOProducts> SelectAllBySearchFields(DAOProducts daoProducts)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprproducts_SelectAllBySearchFields;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("products");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)daoProducts.Id?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@name", SqlDbType.VarChar, 255, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, (object)daoProducts.Name?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@shortname", SqlDbType.VarChar, 255, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, (object)daoProducts.Shortname?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@externalid", SqlDbType.BigInt, 8, ParameterDirection.Input, true, 19, 0, "", DataRowVersion.Proposed, (object)daoProducts.Externalid?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@producttypeid", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoProducts.Producttypeid?? (object)DBNull.Value));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DAOProducts> objList = new List<DAOProducts>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOProducts retObj = new DAOProducts();
						retObj._id					 = Convert.IsDBNull(row["id"]) ? (Int32?)null : (Int32?)row["id"];
						retObj._name					 = Convert.IsDBNull(row["name"]) ? null : (string)row["name"];
						retObj._shortname					 = Convert.IsDBNull(row["shortname"]) ? null : (string)row["shortname"];
						retObj._externalid					 = Convert.IsDBNull(row["externalid"]) ? (Int64?)null : (Int64?)row["externalid"];
						retObj._producttypeid					 = Convert.IsDBNull(row["producttypeid"]) ? (Int32?)null : (Int32?)row["producttypeid"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///DAOProducts daoProducts
		///</parameters>
		public static Int32 SelectAllBySearchFieldsCount(DAOProducts daoProducts)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprproducts_SelectAllBySearchFieldsCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)daoProducts.Id?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@name", SqlDbType.VarChar, 255, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, (object)daoProducts.Name?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@shortname", SqlDbType.VarChar, 255, ParameterDirection.Input, true, 0, 0, "", DataRowVersion.Proposed, (object)daoProducts.Shortname?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@externalid", SqlDbType.BigInt, 8, ParameterDirection.Input, true, 19, 0, "", DataRowVersion.Proposed, (object)daoProducts.Externalid?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@producttypeid", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoProducts.Producttypeid?? (object)DBNull.Value));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Update one row by primary key(s)
		///This method allows the object to update itself in the table products based on its primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Update()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprproducts_UpdateOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_id?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@name", SqlDbType.VarChar, 255, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_name?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@shortname", SqlDbType.VarChar, 255, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_shortname?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@externalid", SqlDbType.BigInt, 8, ParameterDirection.InputOutput, true, 19, 0, "", DataRowVersion.Proposed, (object)_externalid?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@producttypeid", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_producttypeid?? (object)DBNull.Value));

				command.ExecuteNonQuery();

				_id					 = Convert.IsDBNull(command.Parameters["@id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@id"].Value;
				_name					 = Convert.IsDBNull(command.Parameters["@name"].Value) ? null : (string)command.Parameters["@name"].Value;
				_shortname					 = Convert.IsDBNull(command.Parameters["@shortname"].Value) ? null : (string)command.Parameters["@shortname"].Value;
				_externalid					 = Convert.IsDBNull(command.Parameters["@externalid"].Value) ? (Int64?)null : (Int64?)command.Parameters["@externalid"].Value;
				_producttypeid					 = Convert.IsDBNull(command.Parameters["@producttypeid"].Value) ? (Int32?)null : (Int32?)command.Parameters["@producttypeid"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		#endregion

		#region member properties

		public Int32? Id
		{
			get
			{
				return _id;
			}
			set
			{
				_id = value;
			}
		}

		public string Name
		{
			get
			{
				return _name;
			}
			set
			{
				_name = value;
			}
		}

		public string Shortname
		{
			get
			{
				return _shortname;
			}
			set
			{
				_shortname = value;
			}
		}

		public Int64? Externalid
		{
			get
			{
				return _externalid;
			}
			set
			{
				_externalid = value;
			}
		}

		public Int32? Producttypeid
		{
			get
			{
				return _producttypeid;
			}
			set
			{
				_producttypeid = value;
			}
		}

		#endregion
	}
}

#region inline sql procs
namespace Awsd5.DataObjects
{
	public partial class InlineProcs
	{
		internal static string ctprproducts_SelectOne = @"
			-- Select one row based on the primary key(s)
			-- selects all rows from the table
			SELECT 
			[id]
			,[name]
			,[shortname]
			,[externalid]
			,[producttypeid]
			FROM [dbo].[products]
			WHERE 
			[id] = @id
			";

		internal static string ctprproducts_DeleteOne = @"
			-- Delete a row based on the primary key(s)
			-- delete all matching from the table
			DELETE [dbo].[products]
			WHERE 
			[id] = @id
			";

		internal static string ctprproducts_SelectAllByProducttypeid = @"
			-- Select all rows based on a foreign key
			-- selects all rows from the table
			SELECT 
			[id]
			,[name]
			,[shortname]
			,[externalid]
			,[producttypeid]
			FROM [dbo].[products]
			WHERE 
			[producttypeid] = @producttypeid OR ([producttypeid] IS NULL AND @producttypeid IS NULL)
			";

		internal static string ctprproducts_SelectAllByProducttypeidCount = @"
			-- Get count of rows returnable by this query
			-- selects count of all rows from the table
			SELECT COUNT(*)
			FROM [dbo].[products]
			WHERE 
			[producttypeid] = @producttypeid OR ([producttypeid] IS NULL AND @producttypeid IS NULL)
			";

		internal static string ctprproducts_DeleteAllByProducttypeid = @"
			
			-- delete all matching from the table
			DELETE [dbo].[products]
			WHERE 
			[producttypeid] = @producttypeid OR ([producttypeid] IS NULL AND @producttypeid IS NULL)
			";

		internal static string ctprproducts_InsertOne = @"
			-- Insert a new row
			-- inserts a new row into the table
			INSERT [dbo].[products]
			(
			[name]
			,[shortname]
			,[externalid]
			,[producttypeid]
			)
			VALUES
			(
			@name
			,@shortname
			,@externalid
			,@producttypeid
			)
			SELECT 
			@id = [id]
			,@name = [name]
			,@shortname = [shortname]
			,@externalid = [externalid]
			,@producttypeid = [producttypeid]
			FROM [dbo].[products]
			WHERE 
			id = SCOPE_IDENTITY()
			";

		internal static string ctprproducts_SelectAll = @"
			-- Select All rows
			-- selects all rows from the table
			SELECT 
			[id]
			,[name]
			,[shortname]
			,[externalid]
			,[producttypeid]
			FROM [dbo].[products]
			";

		internal static string ctprproducts_SelectAllCount = @"
			
			-- selects count of all rows from the table
			SELECT COUNT(*)
			FROM [dbo].[products]
			";

		internal static string ctprproducts_SelectAllBySearchFields = @"
			
			-- selects all rows from the table according to search criteria
			SELECT 
			[id],
			[name],
			[shortname],
			[externalid],
			[producttypeid]
			FROM [dbo].[products]
			WHERE 
			([id] LIKE @id OR @id is null)
			AND ([name] LIKE @name OR @name is null)
			AND ([shortname] LIKE @shortname OR @shortname is null)
			AND ([externalid] LIKE @externalid OR @externalid is null)
			AND ([producttypeid] LIKE @producttypeid OR @producttypeid is null)
			";

		internal static string ctprproducts_SelectAllBySearchFieldsCount = @"
			-- Get count of rows returnable by this query
			-- selects count of all rows from the table according to search criteria
			SELECT COUNT(*)
			FROM [dbo].[products]
			WHERE 
			([id] LIKE @id OR @id is null)
			AND ([name] LIKE @name OR @name is null)
			AND ([shortname] LIKE @shortname OR @shortname is null)
			AND ([externalid] LIKE @externalid OR @externalid is null)
			AND ([producttypeid] LIKE @producttypeid OR @producttypeid is null)
			";

		internal static string ctprproducts_UpdateOne = @"
			-- Update one row based on the primary key(s)
			-- updates a row in the table based on the primary key
			
			UPDATE [dbo].[products]
			SET
			[name] = @name
			,[shortname] = @shortname
			,[externalid] = @externalid
			,[producttypeid] = @producttypeid
			WHERE 
			[id] = @id
			SELECT 
			@id = [id]
			,@name = [name]
			,@shortname = [shortname]
			,@externalid = [externalid]
			,@producttypeid = [producttypeid]
			FROM [dbo].[products]
			WHERE 
			[id] = @id
			";

	}
}
#endregion
