/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 27.06.2018 13:13:07
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using Awsd5.DataObjects;

namespace Awsd5.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOContainers.
	///</Summary>
	public partial class BOContainers : DATACONN0_BaseBusiness
	{
		#region member variables
		protected Int32? _id;
		protected string _number;
		protected float? _doctara;
		protected float? _docbrutto;
		protected float? _docnetto;
		protected Int32? _weightcount;
		protected DateTime? _w1time;
		protected float? _w1result;
		protected float? _w1tara;
		protected float? _w1brutto;
		protected float? _w1netto;
		protected Int32? _w1scale;
		protected DateTime? _w2time;
		protected float? _w2result;
		protected float? _w2tara;
		protected float? _w2brutto;
		protected float? _w2netto;
		protected Int32? _w2scale;
		protected Int32? _session;
		protected Int32? _receiverid;
		protected Int32? _senderid;
		protected Int32? _productid;
		protected Int32? _operationid;
		protected string _lotnumber;
		protected Int32? _trailid;
		protected Int32? _minesid;
		protected string _zagrnumber;
		protected Int32? _returnid;
		protected Int32? _userid;
		protected Int32? _sessionid;
		protected float? _speed;
		protected Int32? _nplatf;
		protected Int32? _lineid;
		protected Int32? _tvagonid;
		protected byte[] _vid1;
		protected byte[] _vid2;
		protected byte[] _vid3;
		protected Int32? _pr1;
		protected Int32? _pr2;
		protected Int32? _pr3;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOContainers()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int32 id
		///</parameters>
		public BOContainers(Int32 id)
		{
			try
			{
				DAOContainers daoContainers = DAOContainers.SelectOne(id);
				_id = daoContainers.Id;
				_number = daoContainers.Number;
				_doctara = daoContainers.Doctara;
				_docbrutto = daoContainers.Docbrutto;
				_docnetto = daoContainers.Docnetto;
				_weightcount = daoContainers.Weightcount;
				_w1time = daoContainers.W1time;
				_w1result = daoContainers.W1result;
				_w1tara = daoContainers.W1tara;
				_w1brutto = daoContainers.W1brutto;
				_w1netto = daoContainers.W1netto;
				_w1scale = daoContainers.W1scale;
				_w2time = daoContainers.W2time;
				_w2result = daoContainers.W2result;
				_w2tara = daoContainers.W2tara;
				_w2brutto = daoContainers.W2brutto;
				_w2netto = daoContainers.W2netto;
				_w2scale = daoContainers.W2scale;
				_session = daoContainers.Session;
				_receiverid = daoContainers.Receiverid;
				_senderid = daoContainers.Senderid;
				_productid = daoContainers.Productid;
				_operationid = daoContainers.Operationid;
				_lotnumber = daoContainers.Lotnumber;
				_trailid = daoContainers.Trailid;
				_minesid = daoContainers.Minesid;
				_zagrnumber = daoContainers.Zagrnumber;
				_returnid = daoContainers.Returnid;
				_userid = daoContainers.Userid;
				_sessionid = daoContainers.Sessionid;
				_speed = daoContainers.Speed;
				_nplatf = daoContainers.Nplatf;
				_lineid = daoContainers.Lineid;
				_tvagonid = daoContainers.Tvagonid;
				_vid1 = daoContainers.Vid1;
				_vid2 = daoContainers.Vid2;
				_vid3 = daoContainers.Vid3;
				_pr1 = daoContainers.Pr1;
				_pr2 = daoContainers.Pr2;
				_pr3 = daoContainers.Pr3;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOContainers
		///</parameters>
		protected internal BOContainers(DAOContainers daoContainers)
		{
			try
			{
				_id = daoContainers.Id;
				_number = daoContainers.Number;
				_doctara = daoContainers.Doctara;
				_docbrutto = daoContainers.Docbrutto;
				_docnetto = daoContainers.Docnetto;
				_weightcount = daoContainers.Weightcount;
				_w1time = daoContainers.W1time;
				_w1result = daoContainers.W1result;
				_w1tara = daoContainers.W1tara;
				_w1brutto = daoContainers.W1brutto;
				_w1netto = daoContainers.W1netto;
				_w1scale = daoContainers.W1scale;
				_w2time = daoContainers.W2time;
				_w2result = daoContainers.W2result;
				_w2tara = daoContainers.W2tara;
				_w2brutto = daoContainers.W2brutto;
				_w2netto = daoContainers.W2netto;
				_w2scale = daoContainers.W2scale;
				_session = daoContainers.Session;
				_receiverid = daoContainers.Receiverid;
				_senderid = daoContainers.Senderid;
				_productid = daoContainers.Productid;
				_operationid = daoContainers.Operationid;
				_lotnumber = daoContainers.Lotnumber;
				_trailid = daoContainers.Trailid;
				_minesid = daoContainers.Minesid;
				_zagrnumber = daoContainers.Zagrnumber;
				_returnid = daoContainers.Returnid;
				_userid = daoContainers.Userid;
				_sessionid = daoContainers.Sessionid;
				_speed = daoContainers.Speed;
				_nplatf = daoContainers.Nplatf;
				_lineid = daoContainers.Lineid;
				_tvagonid = daoContainers.Tvagonid;
				_vid1 = daoContainers.Vid1;
				_vid2 = daoContainers.Vid2;
				_vid3 = daoContainers.Vid3;
				_pr1 = daoContainers.Pr1;
				_pr2 = daoContainers.Pr2;
				_pr3 = daoContainers.Pr3;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new Containers record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DAOContainers daoContainers = new DAOContainers();
			RegisterDataObject(daoContainers);
			BeginTransaction("savenewBOContainers");
			try
			{
				daoContainers.Number = _number;
				daoContainers.Doctara = _doctara;
				daoContainers.Docbrutto = _docbrutto;
				daoContainers.Docnetto = _docnetto;
				daoContainers.Weightcount = _weightcount;
				daoContainers.W1time = _w1time;
				daoContainers.W1result = _w1result;
				daoContainers.W1tara = _w1tara;
				daoContainers.W1brutto = _w1brutto;
				daoContainers.W1netto = _w1netto;
				daoContainers.W1scale = _w1scale;
				daoContainers.W2time = _w2time;
				daoContainers.W2result = _w2result;
				daoContainers.W2tara = _w2tara;
				daoContainers.W2brutto = _w2brutto;
				daoContainers.W2netto = _w2netto;
				daoContainers.W2scale = _w2scale;
				daoContainers.Session = _session;
				daoContainers.Receiverid = _receiverid;
				daoContainers.Senderid = _senderid;
				daoContainers.Productid = _productid;
				daoContainers.Operationid = _operationid;
				daoContainers.Lotnumber = _lotnumber;
				daoContainers.Trailid = _trailid;
				daoContainers.Minesid = _minesid;
				daoContainers.Zagrnumber = _zagrnumber;
				daoContainers.Returnid = _returnid;
				daoContainers.Userid = _userid;
				daoContainers.Sessionid = _sessionid;
				daoContainers.Speed = _speed;
				daoContainers.Nplatf = _nplatf;
				daoContainers.Lineid = _lineid;
				daoContainers.Tvagonid = _tvagonid;
				daoContainers.Vid1 = _vid1;
				daoContainers.Vid2 = _vid2;
				daoContainers.Vid3 = _vid3;
				daoContainers.Pr1 = _pr1;
				daoContainers.Pr2 = _pr2;
				daoContainers.Pr3 = _pr3;
				daoContainers.Insert();
				CommitTransaction();
				
				_id = daoContainers.Id;
				_number = daoContainers.Number;
				_doctara = daoContainers.Doctara;
				_docbrutto = daoContainers.Docbrutto;
				_docnetto = daoContainers.Docnetto;
				_weightcount = daoContainers.Weightcount;
				_w1time = daoContainers.W1time;
				_w1result = daoContainers.W1result;
				_w1tara = daoContainers.W1tara;
				_w1brutto = daoContainers.W1brutto;
				_w1netto = daoContainers.W1netto;
				_w1scale = daoContainers.W1scale;
				_w2time = daoContainers.W2time;
				_w2result = daoContainers.W2result;
				_w2tara = daoContainers.W2tara;
				_w2brutto = daoContainers.W2brutto;
				_w2netto = daoContainers.W2netto;
				_w2scale = daoContainers.W2scale;
				_session = daoContainers.Session;
				_receiverid = daoContainers.Receiverid;
				_senderid = daoContainers.Senderid;
				_productid = daoContainers.Productid;
				_operationid = daoContainers.Operationid;
				_lotnumber = daoContainers.Lotnumber;
				_trailid = daoContainers.Trailid;
				_minesid = daoContainers.Minesid;
				_zagrnumber = daoContainers.Zagrnumber;
				_returnid = daoContainers.Returnid;
				_userid = daoContainers.Userid;
				_sessionid = daoContainers.Sessionid;
				_speed = daoContainers.Speed;
				_nplatf = daoContainers.Nplatf;
				_lineid = daoContainers.Lineid;
				_tvagonid = daoContainers.Tvagonid;
				_vid1 = daoContainers.Vid1;
				_vid2 = daoContainers.Vid2;
				_vid3 = daoContainers.Vid3;
				_pr1 = daoContainers.Pr1;
				_pr2 = daoContainers.Pr2;
				_pr3 = daoContainers.Pr3;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("savenewBOContainers");
				throw;
			}
		}
		
		///<Summary>
		///Update
		///This method updates one Containers record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOContainers
		///</parameters>
		public virtual void Update()
		{
			DAOContainers daoContainers = new DAOContainers();
			RegisterDataObject(daoContainers);
			BeginTransaction("updateBOContainers");
			try
			{
				daoContainers.Id = _id;
				daoContainers.Number = _number;
				daoContainers.Doctara = _doctara;
				daoContainers.Docbrutto = _docbrutto;
				daoContainers.Docnetto = _docnetto;
				daoContainers.Weightcount = _weightcount;
				daoContainers.W1time = _w1time;
				daoContainers.W1result = _w1result;
				daoContainers.W1tara = _w1tara;
				daoContainers.W1brutto = _w1brutto;
				daoContainers.W1netto = _w1netto;
				daoContainers.W1scale = _w1scale;
				daoContainers.W2time = _w2time;
				daoContainers.W2result = _w2result;
				daoContainers.W2tara = _w2tara;
				daoContainers.W2brutto = _w2brutto;
				daoContainers.W2netto = _w2netto;
				daoContainers.W2scale = _w2scale;
				daoContainers.Session = _session;
				daoContainers.Receiverid = _receiverid;
				daoContainers.Senderid = _senderid;
				daoContainers.Productid = _productid;
				daoContainers.Operationid = _operationid;
				daoContainers.Lotnumber = _lotnumber;
				daoContainers.Trailid = _trailid;
				daoContainers.Minesid = _minesid;
				daoContainers.Zagrnumber = _zagrnumber;
				daoContainers.Returnid = _returnid;
				daoContainers.Userid = _userid;
				daoContainers.Sessionid = _sessionid;
				daoContainers.Speed = _speed;
				daoContainers.Nplatf = _nplatf;
				daoContainers.Lineid = _lineid;
				daoContainers.Tvagonid = _tvagonid;
				daoContainers.Vid1 = _vid1;
				daoContainers.Vid2 = _vid2;
				daoContainers.Vid3 = _vid3;
				daoContainers.Pr1 = _pr1;
				daoContainers.Pr2 = _pr2;
				daoContainers.Pr3 = _pr3;
				daoContainers.Update();
				CommitTransaction();
				
				_id = daoContainers.Id;
				_number = daoContainers.Number;
				_doctara = daoContainers.Doctara;
				_docbrutto = daoContainers.Docbrutto;
				_docnetto = daoContainers.Docnetto;
				_weightcount = daoContainers.Weightcount;
				_w1time = daoContainers.W1time;
				_w1result = daoContainers.W1result;
				_w1tara = daoContainers.W1tara;
				_w1brutto = daoContainers.W1brutto;
				_w1netto = daoContainers.W1netto;
				_w1scale = daoContainers.W1scale;
				_w2time = daoContainers.W2time;
				_w2result = daoContainers.W2result;
				_w2tara = daoContainers.W2tara;
				_w2brutto = daoContainers.W2brutto;
				_w2netto = daoContainers.W2netto;
				_w2scale = daoContainers.W2scale;
				_session = daoContainers.Session;
				_receiverid = daoContainers.Receiverid;
				_senderid = daoContainers.Senderid;
				_productid = daoContainers.Productid;
				_operationid = daoContainers.Operationid;
				_lotnumber = daoContainers.Lotnumber;
				_trailid = daoContainers.Trailid;
				_minesid = daoContainers.Minesid;
				_zagrnumber = daoContainers.Zagrnumber;
				_returnid = daoContainers.Returnid;
				_userid = daoContainers.Userid;
				_sessionid = daoContainers.Sessionid;
				_speed = daoContainers.Speed;
				_nplatf = daoContainers.Nplatf;
				_lineid = daoContainers.Lineid;
				_tvagonid = daoContainers.Tvagonid;
				_vid1 = daoContainers.Vid1;
				_vid2 = daoContainers.Vid2;
				_vid3 = daoContainers.Vid3;
				_pr1 = daoContainers.Pr1;
				_pr2 = daoContainers.Pr2;
				_pr3 = daoContainers.Pr3;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("updateBOContainers");
				throw;
			}
		}
		///<Summary>
		///Delete
		///This method deletes one Containers record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DAOContainers daoContainers = new DAOContainers();
			RegisterDataObject(daoContainers);
			BeginTransaction("deleteBOContainers");
			try
			{
				daoContainers.Id = _id;
				daoContainers.Delete();
				CommitTransaction();
			}
			catch
			{
				RollbackTransaction("deleteBOContainers");
				throw;
			}
		}
		
		///<Summary>
		///ContainersCollection
		///This method returns the collection of BOContainers objects
		///</Summary>
		///<returns>
		///List[BOContainers]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BOContainers> ContainersCollection()
		{
			try
			{
				IList<BOContainers> boContainersCollection = new List<BOContainers>();
				IList<DAOContainers> daoContainersCollection = DAOContainers.SelectAll();
			
				foreach(DAOContainers daoContainers in daoContainersCollection)
					boContainersCollection.Add(new BOContainers(daoContainers));
			
				return boContainersCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///ContainersCollectionCount
		///This method returns the collection count of BOContainers objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 ContainersCollectionCount()
		{
			try
			{
				Int32 objCount = DAOContainers.SelectAllCount();
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///ContainersCollectionFromSearchFields
		///This method returns the collection of BOContainers objects, filtered by a search object
		///</Summary>
		///<returns>
		///List<BOContainers>
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BOContainers> ContainersCollectionFromSearchFields(BOContainers boContainers)
		{
			try
			{
				IList<BOContainers> boContainersCollection = new List<BOContainers>();
				DAOContainers daoContainers = new DAOContainers();
				daoContainers.Id = boContainers.Id;
				daoContainers.Number = boContainers.Number;
				daoContainers.Doctara = boContainers.Doctara;
				daoContainers.Docbrutto = boContainers.Docbrutto;
				daoContainers.Docnetto = boContainers.Docnetto;
				daoContainers.Weightcount = boContainers.Weightcount;
				daoContainers.W1time = boContainers.W1time;
				daoContainers.W1result = boContainers.W1result;
				daoContainers.W1tara = boContainers.W1tara;
				daoContainers.W1brutto = boContainers.W1brutto;
				daoContainers.W1netto = boContainers.W1netto;
				daoContainers.W1scale = boContainers.W1scale;
				daoContainers.W2time = boContainers.W2time;
				daoContainers.W2result = boContainers.W2result;
				daoContainers.W2tara = boContainers.W2tara;
				daoContainers.W2brutto = boContainers.W2brutto;
				daoContainers.W2netto = boContainers.W2netto;
				daoContainers.W2scale = boContainers.W2scale;
				daoContainers.Session = boContainers.Session;
				daoContainers.Receiverid = boContainers.Receiverid;
				daoContainers.Senderid = boContainers.Senderid;
				daoContainers.Productid = boContainers.Productid;
				daoContainers.Operationid = boContainers.Operationid;
				daoContainers.Lotnumber = boContainers.Lotnumber;
				daoContainers.Trailid = boContainers.Trailid;
				daoContainers.Minesid = boContainers.Minesid;
				daoContainers.Zagrnumber = boContainers.Zagrnumber;
				daoContainers.Returnid = boContainers.Returnid;
				daoContainers.Userid = boContainers.Userid;
				daoContainers.Sessionid = boContainers.Sessionid;
				daoContainers.Speed = boContainers.Speed;
				daoContainers.Nplatf = boContainers.Nplatf;
				daoContainers.Lineid = boContainers.Lineid;
				daoContainers.Tvagonid = boContainers.Tvagonid;
				daoContainers.Vid1 = boContainers.Vid1;
				daoContainers.Vid2 = boContainers.Vid2;
				daoContainers.Vid3 = boContainers.Vid3;
				daoContainers.Pr1 = boContainers.Pr1;
				daoContainers.Pr2 = boContainers.Pr2;
				daoContainers.Pr3 = boContainers.Pr3;
				IList<DAOContainers> daoContainersCollection = DAOContainers.SelectAllBySearchFields(daoContainers);
			
				foreach(DAOContainers resdaoContainers in daoContainersCollection)
					boContainersCollection.Add(new BOContainers(resdaoContainers));
			
				return boContainersCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///ContainersCollectionFromSearchFieldsCount
		///This method returns the collection count of BOContainers objects, filtered by a search object
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 ContainersCollectionFromSearchFieldsCount(BOContainers boContainers)
		{
			try
			{
				DAOContainers daoContainers = new DAOContainers();
				daoContainers.Id = boContainers.Id;
				daoContainers.Number = boContainers.Number;
				daoContainers.Doctara = boContainers.Doctara;
				daoContainers.Docbrutto = boContainers.Docbrutto;
				daoContainers.Docnetto = boContainers.Docnetto;
				daoContainers.Weightcount = boContainers.Weightcount;
				daoContainers.W1time = boContainers.W1time;
				daoContainers.W1result = boContainers.W1result;
				daoContainers.W1tara = boContainers.W1tara;
				daoContainers.W1brutto = boContainers.W1brutto;
				daoContainers.W1netto = boContainers.W1netto;
				daoContainers.W1scale = boContainers.W1scale;
				daoContainers.W2time = boContainers.W2time;
				daoContainers.W2result = boContainers.W2result;
				daoContainers.W2tara = boContainers.W2tara;
				daoContainers.W2brutto = boContainers.W2brutto;
				daoContainers.W2netto = boContainers.W2netto;
				daoContainers.W2scale = boContainers.W2scale;
				daoContainers.Session = boContainers.Session;
				daoContainers.Receiverid = boContainers.Receiverid;
				daoContainers.Senderid = boContainers.Senderid;
				daoContainers.Productid = boContainers.Productid;
				daoContainers.Operationid = boContainers.Operationid;
				daoContainers.Lotnumber = boContainers.Lotnumber;
				daoContainers.Trailid = boContainers.Trailid;
				daoContainers.Minesid = boContainers.Minesid;
				daoContainers.Zagrnumber = boContainers.Zagrnumber;
				daoContainers.Returnid = boContainers.Returnid;
				daoContainers.Userid = boContainers.Userid;
				daoContainers.Sessionid = boContainers.Sessionid;
				daoContainers.Speed = boContainers.Speed;
				daoContainers.Nplatf = boContainers.Nplatf;
				daoContainers.Lineid = boContainers.Lineid;
				daoContainers.Tvagonid = boContainers.Tvagonid;
				daoContainers.Vid1 = boContainers.Vid1;
				daoContainers.Vid2 = boContainers.Vid2;
				daoContainers.Vid3 = boContainers.Vid3;
				daoContainers.Pr1 = boContainers.Pr1;
				daoContainers.Pr2 = boContainers.Pr2;
				daoContainers.Pr3 = boContainers.Pr3;
				Int32 objCount = DAOContainers.SelectAllBySearchFieldsCount(daoContainers);
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		#endregion

		#region member properties
		
		public virtual Int32? Id
		{
			get
			{
				 return _id;
			}
			set
			{
				_id = value;
				_isDirty = true;
			}
		}
		
		public virtual string Number
		{
			get
			{
				 return _number;
			}
			set
			{
				_number = value;
				_isDirty = true;
			}
		}
		
		public virtual float? Doctara
		{
			get
			{
				 return _doctara;
			}
			set
			{
				_doctara = value;
				_isDirty = true;
			}
		}
		
		public virtual float? Docbrutto
		{
			get
			{
				 return _docbrutto;
			}
			set
			{
				_docbrutto = value;
				_isDirty = true;
			}
		}
		
		public virtual float? Docnetto
		{
			get
			{
				 return _docnetto;
			}
			set
			{
				_docnetto = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Weightcount
		{
			get
			{
				 return _weightcount;
			}
			set
			{
				_weightcount = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? W1time
		{
			get
			{
				 return _w1time;
			}
			set
			{
				_w1time = value;
				_isDirty = true;
			}
		}
		
		public virtual float? W1result
		{
			get
			{
				 return _w1result;
			}
			set
			{
				_w1result = value;
				_isDirty = true;
			}
		}
		
		public virtual float? W1tara
		{
			get
			{
				 return _w1tara;
			}
			set
			{
				_w1tara = value;
				_isDirty = true;
			}
		}
		
		public virtual float? W1brutto
		{
			get
			{
				 return _w1brutto;
			}
			set
			{
				_w1brutto = value;
				_isDirty = true;
			}
		}
		
		public virtual float? W1netto
		{
			get
			{
				 return _w1netto;
			}
			set
			{
				_w1netto = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? W1scale
		{
			get
			{
				 return _w1scale;
			}
			set
			{
				_w1scale = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? W2time
		{
			get
			{
				 return _w2time;
			}
			set
			{
				_w2time = value;
				_isDirty = true;
			}
		}
		
		public virtual float? W2result
		{
			get
			{
				 return _w2result;
			}
			set
			{
				_w2result = value;
				_isDirty = true;
			}
		}
		
		public virtual float? W2tara
		{
			get
			{
				 return _w2tara;
			}
			set
			{
				_w2tara = value;
				_isDirty = true;
			}
		}
		
		public virtual float? W2brutto
		{
			get
			{
				 return _w2brutto;
			}
			set
			{
				_w2brutto = value;
				_isDirty = true;
			}
		}
		
		public virtual float? W2netto
		{
			get
			{
				 return _w2netto;
			}
			set
			{
				_w2netto = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? W2scale
		{
			get
			{
				 return _w2scale;
			}
			set
			{
				_w2scale = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Session
		{
			get
			{
				 return _session;
			}
			set
			{
				_session = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Receiverid
		{
			get
			{
				 return _receiverid;
			}
			set
			{
				_receiverid = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Senderid
		{
			get
			{
				 return _senderid;
			}
			set
			{
				_senderid = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Productid
		{
			get
			{
				 return _productid;
			}
			set
			{
				_productid = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Operationid
		{
			get
			{
				 return _operationid;
			}
			set
			{
				_operationid = value;
				_isDirty = true;
			}
		}
		
		public virtual string Lotnumber
		{
			get
			{
				 return _lotnumber;
			}
			set
			{
				_lotnumber = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Trailid
		{
			get
			{
				 return _trailid;
			}
			set
			{
				_trailid = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Minesid
		{
			get
			{
				 return _minesid;
			}
			set
			{
				_minesid = value;
				_isDirty = true;
			}
		}
		
		public virtual string Zagrnumber
		{
			get
			{
				 return _zagrnumber;
			}
			set
			{
				_zagrnumber = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Returnid
		{
			get
			{
				 return _returnid;
			}
			set
			{
				_returnid = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Userid
		{
			get
			{
				 return _userid;
			}
			set
			{
				_userid = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Sessionid
		{
			get
			{
				 return _sessionid;
			}
			set
			{
				_sessionid = value;
				_isDirty = true;
			}
		}
		
		public virtual float? Speed
		{
			get
			{
				 return _speed;
			}
			set
			{
				_speed = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Nplatf
		{
			get
			{
				 return _nplatf;
			}
			set
			{
				_nplatf = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Lineid
		{
			get
			{
				 return _lineid;
			}
			set
			{
				_lineid = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Tvagonid
		{
			get
			{
				 return _tvagonid;
			}
			set
			{
				_tvagonid = value;
				_isDirty = true;
			}
		}
		
		public virtual byte[] Vid1
		{
			get
			{
				 return _vid1;
			}
			set
			{
				_vid1 = value;
				_isDirty = true;
			}
		}
		
		public virtual byte[] Vid2
		{
			get
			{
				 return _vid2;
			}
			set
			{
				_vid2 = value;
				_isDirty = true;
			}
		}
		
		public virtual byte[] Vid3
		{
			get
			{
				 return _vid3;
			}
			set
			{
				_vid3 = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Pr1
		{
			get
			{
				 return _pr1;
			}
			set
			{
				_pr1 = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Pr2
		{
			get
			{
				 return _pr2;
			}
			set
			{
				_pr2 = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? Pr3
		{
			get
			{
				 return _pr3;
			}
			set
			{
				_pr3 = value;
				_isDirty = true;
			}
		}
		
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
